### ISSUE TITLE
default to copying across environment variables from the master to the build pod

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/kubernetes-workflow#16]
we should add all environment variables in the master build that start with `BUILD_`, `JOB_` or `GIT_` so that they are also available in the slave build pods. e.g. adding them by default to the generated Pod environment variables.

e.g. these [environment variables](https://github.com/jstrachan/fabric8/blob/e94e2d25dac04477fb1e3a6cc77f3744efb08756/fabric8-maven-plugin/src/main/resources/io/fabric8/maven/environmentAnnotations.properties#L3-L3) such as `BUILD_ID`  really help add better metadata support for linking to build id / build url / git url etc.

Right now we're losing links to the build ID and URL in Java builds in Kubernetes Workflow as they run on the slave and there's no environment variables available

**Comment by iocanel** [comment]
We need a generic way to enrich the build pod and also react to stuff that happen inside it.

I am going to look what is the jenkins way of doing it and apply it to this use case.

**Comment by rawlingsj** [comment]
it would also be good to get all envars that were available to the master, for example this shows trying to use the DOCKER_REGISTRY_SERVICE_HOST env var inside and out side a node..

```

def outside = "${env.DOCKER_REGISTRY_SERVICE_HOST}:${env.DOCKER_REGISTRY_SERVICE_PORT}"
node{
    echo "defined outside " + outside
    
    def inside = "${env.DOCKER_REGISTRY_SERVICE_HOST}:${env.DOCKER_REGISTRY_SERVICE_PORT}"
    echo "defined inside " + inside

}
```

output...

```
Started by user anonymous
[Workflow] Allocate node : Start
Still waiting to schedule task
Waiting for next available executor
Running on 1ff540828c1a in /home/jenkins/workspace/workspace/test
[Workflow] node {
[Workflow] echo
defined outside null:null
[Workflow] echo
defined inside 172.30.122.113:5000
[Workflow] } //node
[Workflow] Allocate node : End
[Workflow] End of Workflow
Finished: SUCCESS
```

**Comment by jstrachan** [comment]
maybe we have a default regular expression of env vars that get auto-added to the generated Pod.container.envVars list unless an empty list is specified? i.e. explicit env vars should always win, but by default folks would expect stuff thats in the master to be in the slave pod

**Comment by jstrachan** [comment]
the other option is we just treat these env vars as being the special list of values - which the user can disable if they wish
https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables
